### ISSUE TITLE
Invalid validation IsChildOf

### ISSUE THREAD

**Issue by janssenMA** [psmacchia/NDepend.Path#4]
The method **IsChildOf** returns an invalid result in the following test-case:
`parentDirectory = new String("D:/Foo").ToAbsoluteDirectoryPath();`
`m_PathString = new String("D:/Foo bar").ToAbsoluteDirectoryPath();`

```
public bool IsChildOf(IDirectoryPath parentDirectory) {
            Debug.Assert(parentDirectory != null);
            string parentPathLowerCase = parentDirectory.ToString().ToLower();
            string thisPathLowerCase = m_PathString.ToLower();
            ...
            return thisPathLowerCase.IndexOf(parentPathLowerCase) == 0;
}
```

 thisPathLowerCase.IndexOf(parentPathLowerCase) === 0 will result in `true`, but `m_PathString` is no child of `parentDirectory`.

**Comment by ndepend** [comment]
Fixed, thanks for this feedback!

https://github.com/psmacchia/NDepend.Path/commit/63f94840e552db181ff215c9dbca62e2c418757c

Unfortunately github wasn't showing up this commit straight, so I revert it a first time, and then both commits shown up, so I reverted it again.

https://github.com/psmacchia/NDepend.Path/commit/2c18a35c63644f740671da888d1aa64203931cd0
https://github.com/psmacchia/NDepend.Path/commit/8504c6b2fa52af54a5ab2e42f88df68c0f05433f

Not sure if one needs to wait until github show a commit? Anyway I downloaded the zip and it looks like the fix is in there.
